### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KSKPAPA** [PyrogramMod/PyrogramMod#11]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I think its a pyrogram issue.

### Steps to reproduce

Not known.

### Code example

```python
[25-Nov-23 18:34:51 - ERROR] - pyrogram.dispatcher - 'ChannelForbidden' object has no attribute 'chat_id'
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/opt/venv/lib/python3.11/site-packages/pytgcalls/mtproto/pyrogram_client.py", line 98, in on_update
    chat_id = self.chat_id(data2[update.chat_id])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pytgcalls/mtproto/bridged_client.py", line 98, in chat_id
    return -input_peer.chat_id
            ^^^^^^^^^^^^^^^^^^
AttributeError: 'ChannelForbidden' object has no attribute 'chat_id'
```
```


### Logs

```shell
[25-Nov-23 18:34:51 - ERROR] - pyrogram.dispatcher - 'ChannelForbidden' object has no attribute 'chat_id'
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/opt/venv/lib/python3.11/site-packages/pytgcalls/mtproto/pyrogram_client.py", line 98, in on_update
    chat_id = self.chat_id(data2[update.chat_id])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pytgcalls/mtproto/bridged_client.py", line 98, in chat_id
    return -input_peer.chat_id
            ^^^^^^^^^^^^^^^^^^
AttributeError: 'ChannelForbidden' object has no attribute 'chat_id'
```
```

**Comment by null-nick** [comment]
@KSKPAPA I need more information to reproduce this error so I can fix it as quickly as possible.

**Comment by KSKOP69** [comment]
> @KSKPAPA I need more information to reproduce this error so I can fix it as quickly as possible.

Im using this repo and got this error.

https://github.com/Pranav-Saraswat/Testing-Alpha.git
